// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"stream-service/pkg/api"
	"stream-service/pkg/api/service"
	"stream-service/pkg/config"
	"stream-service/pkg/db"
	"stream-service/pkg/repository"
	"stream-service/pkg/usecase"
)

// Injectors from wire.go:

func InitializeAPI(cfg config.Config) (*api.Server, error) {
	gormDB, err := db.ConnectDatabase(cfg)
	if err != nil {
		return nil, err
	}
	streamRepository := repository.NewStreamRepository(gormDB)
	streamUseCase := usecase.NewStreamUseCase(streamRepository)
	streamServiceServer := service.NewStreamService(streamUseCase)
	server, err := api.NewServerGRPC(cfg, streamServiceServer)
	if err != nil {
		return nil, err
	}
	return server, nil
}
